version: '3.8'

services:
  backend-dev:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "8001:8001"
    environment:
      - ENVIRONMENT=development
      - DATABASE_URL=sqlite:///./dev_pdfs.db
      - UPLOAD_DIR=dev_uploaded_pdfs
      - FRONTEND_URL=http://localhost:3000
      - DEBUG=true
      - LOG_LEVEL=DEBUG
    volumes:
      - ./backend:/app
      - dev_uploaded_pdfs:/app/dev_uploaded_pdfs
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8001

  frontend-dev:
    build:
      context: ./frontend/react_app
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8001
    volumes:
      - ./frontend/react_app:/app
      - /app/node_modules
    depends_on:
      - backend-dev

volumes:
  dev_uploaded_pdfs:
