[phases.setup]
nixPkgs = ["python39"]

[phases.install]
cmds = ["pip install -r backend/requirements.txt"]

[phases.build]
cmds = ["echo 'Build completed'"]

[start]
cmd = "uvicorn backend.main:app --host 0.0.0.0 --port $PORT" 