[phases.setup]
nixPkgs = ["python39", "poetry", "tesseract", "poppler_utils"]

[phases.install]
cmds = [
  "pip install --upgrade pip",
  "pip install -r requirements.txt"
]

[phases.build]
cmds = [
  "mkdir -p uploaded_pdfs",
  "echo 'Build completed'"
]

[start]
cmd = "python railway_start.py" 